sudo: required
services:
  - docker 

#build test
before_install:
  - docker build -t ramkumarsingh/udemycomplexdocker-test -f ./myclientapp/Dockerfile.dev ./myclientapp

#run test
script:
  - docker run -e CI=true ramkumarsingh/udemycomplexdocker-test npm test

#build prod version
after_success:
  - docker build -t ramkumarsingh/udemycomplexdocker-client ./myclientapp 
  - docker build -t ramkumarsingh/udemycomplexdocker-nginx ./mynginx
  - docker build -t ramkumarsingh/udemycomplexdocker-server ./myserverapp
  - docker build -t ramkumarsingh/udemycomplexdocker-worker ./myworkerapp   

#push image to docker hub
  #login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push image
  - docker push ramkumarsingh/udemycomplexdocker-client 
  - docker push ramkumarsingh/udemycomplexdocker-nginx
  - docker push ramkumarsingh/udemycomplexdocker-server
  - docker push ramkumarsingh/udemycomplexdocker-worker
